### ISSUE TITLE
Do the op/ui files belong in op/ui/autoconvert?

### ISSUE THREAD

**Issue by MarkRivers** [epics-modules/ip#14]
The edl files are in op/edl/autoconvert and the opi files are in op/opi/autoconvert.  Should the ui files be in op/ui/autoconvert, or are these manually tweaked?  I would like to add the op/Makefile so we can automatically convert in the future when new files are added or medm files are edited.  But first I want to have the ui files in the correct location.

**Comment by prjemian** [comment]
The manually-tweaked files are in `op/ui` while `op/Makefile` only updates `op/ui/autoconvert` (from `op/adl`)

**Comment by MarkRivers** [comment]
> The manually-tweaked files are in op/ui while op/Makefile only updates op/ui/autoconvert (from op/adl)

I understand that.  That would imply that all ~100 files in op/ui were manually tweaked, and there no autoconverted files because the autoconvert directory is empty.  I find this highly doubtful.  I have done a "git log" on a number of the files, and the last commit for each was Sept. 11, 2014 with the same commit message.

**Comment by Engbretson** [comment]
Pete’s answer is the convention (from a recent group meeting) that bcda would like to be consistent everywhere so that the scripts which create/autoconvert the opi’s and ui’s  will always be up to date with the adl files, but if someone tweaks any of these files, they don’t get trashed by an adl update. So the path hierarchy of where to look is known.

Which implies that across the board, only adl files should be in the expected locations and everything else should now be living in one of the autoconvert locations. There should never be anything in ui or edl since that already implies that there are not consistent with adl.

**Comment by timmmooney** [comment]
I agree.  I'm going to move all the ui files in op/ui to op/ui/autoconvert.


Tim Mooney (mooney@aps.anl.gov) (630)252-5417
Beamline Controls Group (www.aps.anl.gov)
Advanced Photon Source, Argonne National Lab

________________________________

**Comment by MarkRivers** [comment]
> There should never be anything in ui or edl since that already implies that there are not consistent with adl. 

I don't think this is quite correct. ui or edl can contain completely new files that exploit the features of that OPI and hence cannot be represented in medm.  They could also contain "tweaked" versions of the converted screens, although I would discourage this since one will need to decide which to copy to a distribution directory.

**Comment by Engbretson** [comment]
Hmmm, your correct. But this would mean having at least *3* levels of redirection – the version converted from ADL, the native enhanced feature version, and then beam line modifications/ working versions.

**Comment by keenanlang** [comment]
Fixed with the following commits:

a5d1f3c
eeebbf8
44135ef
793e571
6c107d2
ec1eda2
74b699e
de0deb5
efd44a4
6d6287a
